POST http://127.0.0.1:5353/users
Content-Type: application/json

{
  "email": "rose@mail.com",
  "firstname": "Rose",
  "lastname": "Doe",
  "password": "rose12345",
  "repeatedPassword": "rose12345"
}

###

GET http://127.0.0.1:5353/users?limit=90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2YzBhOTdjNmNhY2Y1YWUwNTJkYWQiLCJlbWFpbCI6InJvc2VAbWFpbC5jb20iLCJpYXQiOjE2NzM5NzA1Mzl9.wOk6uIvqU9ZeSdS9pOfFMM42XhHUhfeN-kti6LYYq78

###

POST http://127.0.0.1:5353/token
Content-Type: application/json

{
  "email": "rose@mail.com",
  "password": "rose12345"
}

###

POST http://127.0.0.1:5353/shoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2YzBhOTdjNmNhY2Y1YWUwNTJkYWQiLCJlbWFpbCI6InJvc2VAbWFpbC5jb20iLCJpYXQiOjE2NzQxMTk2MTh9.WFyK_RxKmdpGkMOEh5r7ICDER4IUC_vAuBKefeXjDqA

{
  "title": "Vend puma bon état",
  "brand": "Puma",
  "model": "Special Edition",
  "price": 85,
  "pictures": [
    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.solecollector.com%2Fcomplex%2Fimage%2Fupload%2Fzgjc5ijooqtwir1ccspq.jpg&f=1&nofb=1&ipt=6639b88daa5f1fb1f71ec57ad81479866c8535ecc0af07ec594ae6969156465d&ipo=images"
  ],
  "color": "9384F3",
  "condition": "worn",
  "size": 35
}

###

GET http://127.0.0.1:5353/shoes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2YzBhOTdjNmNhY2Y1YWUwNTJkYWQiLCJlbWFpbCI6InJvc2VAbWFpbC5jb20iLCJpYXQiOjE2NzQxMTk2MTh9.WFyK_RxKmdpGkMOEh5r7ICDER4IUC_vAuBKefeXjDqA

###

PATCH http://127.0.0.1:5353/shoes/63c95cf22345190a71ee8057
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2YzBhOTdjNmNhY2Y1YWUwNTJkYWQiLCJlbWFpbCI6InJvc2VAbWFpbC5jb20iLCJpYXQiOjE2NzQxMTk2MTh9.WFyK_RxKmdpGkMOEh5r7ICDER4IUC_vAuBKefeXjDqA

{
  "color": "6537AB",
  "price": 69.99
}

###

DELETE http://127.0.0.1:5353/shoes/63c95fad9752b95ad873f077
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M2YzBhOTdjNmNhY2Y1YWUwNTJkYWQiLCJlbWFpbCI6InJvc2VAbWFpbC5jb20iLCJpYXQiOjE2NzQxMTk2MTh9.WFyK_RxKmdpGkMOEh5r7ICDER4IUC_vAuBKefeXjDqA
